input {
  tcp {
    # Socket port
    port => 5600
    codec => json_lines
  }
}

filter {
  if ![appName] {
    mutate {
      add_field => { "appName" => "default-service" }
    }
  }
  mutate {
    lowercase => [ "appName" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservices-log-%{appName}-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}