# --- Root Project Configuration ---
sonar.projectKey=micro-kube
sonar.projectName=Micro Kube Project
sonar.projectVersion=1.0-SNAPSHOT

# --- SonarQube Server Connection ---
sonar.host.url=http://localhost:9000
sonar.login=sqa_8097680eb1db35d6a5ae779a5ca19cb2cfe50a9c

# --- Global Encoding ---
sonar.sourceEncoding=UTF-8

# --- Define Modules ---
sonar.modules=api-gateway,authentication-service,account-service,mail-service,product-service,order-service,payment-service