spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB:order_db}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}
    checkout-order: checkout-order-topic
    update-inventory: update-inventory-topic
    update-order-status: update-order-status-topic
    order-success: order-success-topic

api:
  internal:
    paymentUrl: http://localhost:8086
    saleOrderUrl: http://localhost:8087/sale-order

stripe:
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_51TJExhBeYZyaJ1oY5UuY4UpAhIBcdnysQGblVG7cjErPCH71nQ4sElBaNehePkzDGSsLITQITkJczluzP33JNHDv00kketjpzN}

openapi:
  service:
    api-docs: order-service
    server: http://localhost:${server.port}
    title: Order service
    version: 1.0.0