# --- Module Configuration ---
sonar.projectKey=micro-kube:payment-service
sonar.projectName=Payment Service

# --- Source and Test Paths ---
sonar.sources=src/main
# sonar.tests=src/test

# --- Compiled Binaries Path ---
sonar.java.binaries=target/classes
# sonar.java.test.binaries=target/test-classes

# --- Exclusions ---
sonar.exclusions=**/target/**,**/*.jar,**/*Generated*.java,**/proto/**

# --- Code Coverage (JaCoCo) ---
# sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
